version: "3.8"

services:
    mongodb:
        image: mongo:latest
        restart: always
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
        volumes:
            - mongo_data:/data/db

    backend:
        build:
            context: ./Backend
            dockerfile: dockerfile
        restart: always
        ports:
            - "8080:8080"
        environment:
            SPRING_DATA_MONGODB_HOST: mongodb
            SPRING_DATA_MONGODB_PORT: 27017
            SPRING_DATA_MONGODB_DATABASE: eleicoesdb
            SPRING_DATA_MONGODB_USERNAME: admin
            SPRING_DATA_MONGODB_PASSWORD: admin
        depends_on:
            - mongodb

    frontend:
        build:
            context: ./Frontend
            dockerfile: dockerfile
        restart: always
        ports:
            - "3000:3000"
        environment:
            VITE_API_URL: http://backend_service:8080
        depends_on:
            - backend

volumes:
    mongo_data:
